### ISSUE TITLE
Code generation issues

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/topological_inventory-api#100]
Due to the use of shared "parameters" in object "definitions" the code generator issues warnings

```
[main] WARN  o.o.codegen.DefaultCodegen - Error obtaining the datatype from ref:#/parameters/ID. Default to 'object'
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: #/parameters/ID
```
and produces incorrect object definitions, anything that it cannot understand it converts to a object (hash)

For example the Flavor object has these simple string properties id, source_id,tenant_id
   
![screen shot 2019-01-23 at 4 13 14 pm](https://user-images.githubusercontent.com/6452699/51637449-dc339900-1f29-11e9-9bc0-54cbb9bddab6.png)

The id, tenant_id and source_id should have been strings

This stems from the use of inheritance from parameters in definitions. The editor can show it but the code generator cannot handle it.

https://github.com/ManageIQ/topological_inventory-api/blob/59b3c6c65903cc10a38391cd1f633cf1f474c782/public/doc/swagger-2-v0.0.1.yaml#L1584

This applies to most of the object definitions where ID is being reused from parameter section.

**Comment by bdunne** [comment]
Interesting, the online editor seems to parse it without trouble..
![image](https://user-images.githubusercontent.com/651659/51851206-6cd6f400-22f1-11e9-9a28-af967c7a33a5.png)

**Comment by mkanoor** [comment]
I am guessing parameters are always for inbound operations, to locate fields in the URL path, Header or body and never used on the client side.
The client side is purely controlled by the definition sections, which has all the model definitions. When you generate client code there is no documentation for Parameters.

So you can create an ID object in the definition object and then use it as an allOf
```
definitions:
....
IDObject:
          type: object
          properties:
                  id:  
                          title: ID Of object
                          type: string
                          readOnly: true 
                  tenant_id:
                          title: ID Of object
                          type: string
                          readOnly: true 
```

And do an inheritance using allOf
```
Container:
    title: "Container Object"
    allOf:
      - $ref: "#/definitions/IDObject"
      - title: Extra objects
        type: object
        properties:
          name:
            type: string
            readOnly: true
            example: docker-build
          cpu_limit:
            type: number
            format: double
            readOnly: true
          cpu_request:
            type: number
            format: double
            readOnly: true
```
Which will give you the id and tenant_id from the parent object
